### Regex expression 학습

학습 날짜 : 2019년 04월 07일

학습 장소 : 프로그래머스 - 정규표현식 사이트

학습 언어 : python3

### 한글 고르기

In [4]:
import re

def regex_practice(regex):
    
    search_target = '''Luke Skywarker 02-123-4567 luke@daum.net
    다스베이더 070-9999-9999 darth_vader@gmail.com
    princess leia 010 2454 3457 leia@gmail.com'''
    
    result = re.findall(regex, search_target)
    print("\n".join(result))

In [5]:
# 빈칸에 정규표현식을 적습니다.
regex = r'[가-힣]+'

regex_practice(regex)

다스베이더


### 기타 대표문자

- 숫자(\d)나 글자(\w)이외에도 다양한 대표 문자가 있습니다.
  - \s 공백 문자(스페이스, 탭, 뉴라인)
  - \S 공백 문자를 제외한 문자
  - \D 숫자를 제외한 문자
  - \W 글자 대표 문자를 제외한 글자들(특수문자, 공백 등)

In [10]:
# 공백 출력
regex = r'\s+'
regex_practice(regex)

In [11]:
# 문자열 출력
regex = r'\S+'
regex_practice(regex)

In [12]:
# 숫자를 제외한 문자
regex = r'\D+'
regex_practice(regex)

In [40]:
# 글자 대표 문자를 제외한 글자들(특수 문자, 공백 등)
regex = r'\W+'
regex_practice(regex)

[' ', ' ', '-', '-', ' ', '@', '.', '\n    ', ' ', '-', '-', ' ', '@', '.', '\n    ', ' ', ' ', ' ', ' ', ' ', '@', '.']


### 1강 정규표현식 사용해 보기

정규표현식은 문자열에서 특정 패턴을 만족하는 부분을 찾아낼 때 사용합니다. 예를 들어 볼까요? 스타워즈 주인공들의 주소록에서 전화번호를 찾아봅시다. 주소록은 코드 5번째 줄 search_target 변수에 적어두었습니다.

사람 이름
전화번호
이메일
이 적힌 주소록에서, 전화번호만 찾는 정규표현식은 다음과 같습니다.

"0\d{1,2}[ -]?\d{3,4}[ -]?\d{3,4}"

빈칸에 이 정규표현식 적어 [실행] 버튼을 눌러보세요.

출력을 확인해 보면, search_target에 들어있는 모든 전화번호를 찾아내서 한 줄씩 출력하는 걸 알 수 있습니다.


In [15]:
regex = r'0\d{1,2}[ -]?\d{3,4}[ -]?\d{3,4}'
regex_practice(regex)

02-123-4567
070-9999-9999
010 2454 3457


### 2강 - 대표문자 - 숫자
전화번호를 찾기 위한 첫 단계는 숫자를 찾아내는 겁니다.

\d는 숫자를 대표하는 정규표현식입니다. 이때 d는 digit을 뜻합니다.

빈칸에 \d를 입력하고 [실행]해 보세요. Output으로 search_target에 들은 모든 숫자가 한 줄씩 나올 겁니다.

In [16]:
regex = r'\d'
regex_practice(regex)

0
2
1
2
3
4
5
6
7
0
7
0
9
9
9
9
9
9
9
9
0
1
0
2
4
5
4
3
4
5
7


### 2강 - 대표문자 - 글자
\w는 글자를 대표하는 정규표현식입니다. \w는

- a, b, c, 가, 나, 다, 1, 2와 같은 문자와 숫자를 포함합니다.
- 특수문자는 포함하지 않지만, _(언더스코어)는 포함합니다.

빈칸에 \w를 입력하고 [실행]해 보세요. Output으로 search_target에 들은 모든 문자와 숫자가 한 줄씩 나올 겁니다.

In [18]:
regex = r'\w'
regex_practice(regex)

### 3강 횟수 정하기 - 하나 이상

\d는 숫자를 한글자만 찾습니다. 그런데, 전화번호를 구성하는 043이나 2568같이 연결된 숫자를 찾고 싶을 때는 어떻게 해야 할까요?

그럴 땐 +를 이용하면 됩니다. +는 하나 혹은 그 이상 연결된이라는 뜻입니다. 따라서 \d+는 하나 혹은 그 이상 연결된 숫자를 의미합니다.

빈칸에 \d+를 입력하고 [실행]해 보세요. Output으로 search_target에 들은 모든 연결된 숫자가 한 줄씩 나올 겁니다.

In [20]:
# + 를 사용하여 하나 혹은 그 이상 연결된 숫자를 파악
regex = r'\d+'
regex_practice(regex)

02
123
4567
070
9999
9999
010
2454
3457


### 3강 횟수 정하기 - 0개 이상

정규표현식으로 010, 123, 456 중 자연수를 찾으려면 어떻게 해야 할까요? 자연수는

0으로 시작하지 않으니 자연수의 첫자리는 반드시 1 ~ 9 중에 하나이어야 합니다.
그다음 자리부터는 0~9 사이의 숫자가 나올 수도 있고, 나오지 않을 수도 있지요.
다시 말해, 자연수는 다음과 같이 표현할 수 있습니다.

1. 처음에 1~9중 하나의 숫자가 나온 다음
2. 그 뒤에는 숫자가 0개 이상 나오면

In [22]:
# *은 0개 이상이라는 뜻입니다. 따라서 \d*는 숫자가 0개 이상이다를 의미합니다. 이를 이용하면 자연수는 [1-9]\d*로 표현할 수 있습니다.
# 빈칸에 [1-9]\d*를 입력하고 [실행]해 보세요. Output으로 search_target에 들은 모든 자연수가 한 줄씩 나올 겁니다.
# 숫자 1~9 0개 이상의 숫자 조합
# [1-9]\d+ 하면 2 가 나오질 않음

regex = r'[1-9]\d*'
regex_practice(regex)

2
123
4567
70
9999
9999
10
2454
3457


### 3강 횟수 정하기 - 있거나 없나가(1)
전화번호는 -을 포함하거나, 포함하지 않을 수 있습니다. 예를 들어, 다음은 모두 유효한 전화번호입니다.

021234567
02-123-4567

따라서 전화번호는 연속되는 숫자 3 ~ 4개 사이에 -가 있거나 없다고 표현할 수 있습니다.

?는 '있거나 없거나'라는 뜻입니다. 

따라서 -?는 -가 있거나 없다를 의미합니다. 

따라서 이를 연속하는 숫자는 \d+와 조합하면 전화번호를 찾는 정규표현식을 만들 수 있습니다.


\d+-?\d+-?\d+

In [24]:
def regex_practice(regex):
    
    search_target = '''Luke Skywarker 02-123-4567 luke@daum.net
    다스베이더 070-9999-9999 darth_vader@gmail.com
    princess leia 010 2454 3457 leia@gmail.com'''
    
    result = re.findall(regex, search_target)
    print(result)

In [25]:
# 숫자 + 있거나 없거나 + 숫자 + 있거나 없거나 + 숫자

regex = r'\d+-?\d+-?\d+'
regex_practice(regex)

['02-123-4567', '070-9999-9999', '010', '2454', '3457']


### 3강 횟수 정하기 - 있거나 없거나(2)

앞에서 배운 \d+-?\d+-?\d+ 정규표현식은 한계가 있습니다. 010 2454 3457과 같이 공백이 포함된 전화번호를 찾을 수 없지요.

021234567
02-123-4567
010 2454 3457

모든 전화번호를 찾으려면

"-가 있거나 없다는 조건이 아니라"

"- 또는 공백이 있거나 없다는 조건을 써야 합니다."

In [28]:
# [- ]? 를 주목하자 - 옆에 공백이 있다.
# - 또는 (공백)이 있거나 없다는 조건은 [- ]?로 표현할 수 있습니다.

regex = r'\d+[- ]?\d+[- ]?\d+'
regex_practice(regex)

['02-123-4567', '070-9999-9999', '010 2454 3457']


### 3강 횟수 정하기 - n번(1)
앞서 배운 \d+[- ]?\d+[- ]?\d+ 정규표현식으로는 전화번호를 찾는데 한계가 있습니다. 

0030589-5-95826과 같이 연결된 숫자가 너무 많은 문자열도 전화번호라고 인식합니다.

코드를 실행해서 결과를 확인해 보세요. 다음 강의에서는 이를 해결할 방법을 알아보겠습니다.

In [29]:
def regex_exp(regex):
    
    search_target = '''이상한 전화번호 0030589-5-95826
    Luke Skywarker 02-123-4567 luke@daum.net
    다스베이더 070-9999-9999 darth_vader@gmail.com
    princess leia 010 2454 3457 leia@gmail.com'''
    
    result=re.findall(regex,search_target)
    print(result)

### 3강 횟수 정하기 - n번(2)

{숫자}는 `숫자`번 반복한다는 뜻입니다. 예를 들어 \d{2}는 숫자가 연속 두 번 나온다는 뜻입니다.

빈칸에 \d{2}[- ]?\d{3}[- ]?\d{4}를 입력하고 [실행]해 보세요.

In [30]:
regex = r'\d{2}[- ]?\d{3}[- ]?\d{4}'
regex_exp(regex)

['02-123-4567']


### 3강 횟수 정하기 - n~m번

앞서 배운 \d{2}[- ]?\d{3}[- ]?\d{4} 정규표현식으로는 전화번호를 찾는데 한계가 있습니다. 전화번호의 첫 부분에 숫자가 3번(010 2454 3457) 나오는 경우를 인식하지 못하지요.

{숫자1, 숫자2}는 숫자1부터 숫자2까지 반복한다는 뜻입니다. 예를 들어, \w{2,3}는 문자가 2 ~ 3번 나온다는 뜻입니다.

전화번호의 자릿수는 다음과 같습니다. 따라서 전화번호는 \d{2,3}[- ]?\d{3,4}[- ]?\d{4}와 같이 표현할 수 있습니다.

In [31]:
regex = r'\d{2,3}[- ]?\d{3,4}[- ]?\d{4}'
regex_exp(regex)

['02-123-4567', '070-9999-9999', '010 2454 3457']


### 4강 고르기 - 몇 개 중에 고르기

알파벳 중에 소문자 모음(a,e,i,o,u)만 고르고 싶을 땐 어떻게 할까요?

그럴 때는 [aeiou]라고 적어주세요. 정규표현식에서 대괄호[ ] 안에 글자를 넣으면 해당 글자를 모두 선택할 수 있습니다.

빈칸에 [aeiou]를 입력하고 [실행]해 보세요. Output으로 search_target에 들은 모든 소문자 알파벳이 한 줄씩 나올 겁니다.

In [36]:
def regex_select(regex):
    
    search_target = '''Luke Skywarker 02-123-4567 luke@daum.net
    다스베이더 070-9999-9999 darth_vader@gmail.com
    princess leia 010 2454 3457 leia@gmail.com'''
    
    result=re.findall(regex,search_target)
    print("\n".join(result))

In [37]:
regex = r'[aeiou]'
regex_select(regex)

u
e
a
e
u
e
a
u
e
a
a
e
a
i
o
i
e
e
i
a
e
i
a
a
i
o


### 4강 고르기 - 범위에서 고르기(1)
소문자 알파벳만 고르고 싶을 땐 어떻게 할까요? [abcdefghijklmnopqrlstuvwxyz]처럼 대괄호 안에 소문자를 모두 나열할 수도 있지만 뭔가 찜찜하지요.

우리는 간단히 [a-z]를 쓰도록 합시다. [a-z]는 a부터 z까지 글자를 모두 선택하라는 의미입니다.

빈칸에 [a-z]를 입력하고 [실행]해 보세요. Output으로 search_target에 들은 모든 소문자 알파벳이 한 줄씩 나올 겁니다.

In [38]:
regex = r'[a-z]'
regex_select(regex)

u
k
e
k
y
w
a
r
k
e
r
l
u
k
e
d
a
u
m
n
e
t
d
a
r
t
h
v
a
d
e
r
g
m
a
i
l
c
o
m
p
r
i
n
c
e
s
s
l
e
i
a
l
e
i
a
g
m
a
i
l
c
o
m


### 4강 고르기 - 범위에서 고르기(2)
연속된 영어 소문자를 찾으려면 어떻게 할까요?

소문자를 뜻하는 [a-z]와 반복을 뜻하는 +를 붙여 => [a-z]+를 씁니다.

빈칸에 [a-z]+를 입력하고 [실행]해 보세요. Output으로 search_target에 들은 모든 연속된 소문자가 한 줄씩 나올 겁니다.

In [39]:
regex = r'[a-z]+'
regex_select(regex)

uke
kywarker
luke
daum
net
darth
vader
gmail
com
princess
leia
leia
gmail
com


### 4강 고르기 - 한글 고르기

한글 단어를 찾으려면 어떻게 할까요?

한글의 첫 번째 글자는 가이고 마지막 글자는 힣입니다. 따라서 한글은 [가-힣]으로 찾을 수 있습니다.1

빈칸에 [가-힣]+를 입력하고 [실행]해 보세요. Output으로 search_target에 들은 모든 한글 단어가 한 줄씩 나올 겁니다.

단, 이 방식으로는 ㄱㄴㄷ이나 ㅏㅑㅓㅕ같은 낱글자는 찾을 수 없습니다.

- 가장 위에서 진행하였음